name: unittests
on: [push, pull_request]
jobs:
  unittests:
    name: "Python unit tests"
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v4
      - run: pip3 install -e "./report-generator/[test]"

